// database.idl: database의 IDL 소스
//

// 이 파일은 MIDL 도구에 의해 처리되어
// 형식 라이브러리(database.tlb) 및 마샬링 코드를 생성합니다.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(962ce875-0c26-41cb-8f6b-424a0dabbc0c),
	version(1.0),
]
library databaseLib
{
	importlib("stdole2.tlb");
};

